Repository rajdeepf1/Capstone-Project, pull requests merged in 2023-02, with the labels that each got.

#23 Sohail branch
  .DS_Store
  .idea/misc.xml
  app/.DS_Store
  app/src/.DS_Store
Labels: medium

#24 Rajdeep branch
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/.DS_Store
  app/src/main/java/com/example/pizza_singh_capstone_project/.DS_Store
  app/src/main/java/com/example/pizza_singh_capstone_project/activities/ProductDetailsActivity.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/activities/ProductListActivity.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/adapters/HomeGridAdapter.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/adapters/ProductListAdapter.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/factories/HomeFactory.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/factories/ProductListFactory.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/fragments/HomeFragment.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/fragments/LoginFragment.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/interfaces/BaseResponse.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/interfaces/NetworkResult.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/models/BannersModel.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/models/CategoriesModel.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/models/LoginSignupModel.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/models/ProductModel.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/repositories/HomeRepository.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/repositories/LoginSignUpRepository.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/repositories/ProductListRepository.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/utils/Collections.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/viewmodels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/viewmodels/LoginFragmentViewModel.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/viewmodels/ProductListViewModel.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/viewmodels/SignUpFragmentViewModel.kt
  app/src/main/res/anim/anim.xml
  app/src/main/res/layout/activity_product_details.xml
  app/src/main/res/layout/activity_product_list.xml
  app/src/main/res/layout/custom_product_list_layout.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/grid_item.xml
Labels: long

#25 Remove .DS_Store from everywhere
  .DS_Store
  .gitignore
  app/.DS_Store
  app/src/.DS_Store
  app/src/main/.DS_Store
  app/src/main/java/.DS_Store
  app/src/main/java/com/.DS_Store
  app/src/main/java/com/example/.DS_Store
  app/src/main/java/com/example/pizza_singh_capstone_project/.DS_Store
  app/src/main/java/com/example/pizza_singh_capstone_project/activities/ProductDetailsActivity.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/activities/ProductListActivity.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/adapters/ProductListAdapter.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/models/ProductModel.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/repositories/ProductListRepository.kt
  app/src/main/res/.DS_Store
  app/src/main/res/drawable/.DS_Store
  app/src/main/res/drawable/nonveg.xml
  app/src/main/res/drawable/veg.xml
  app/src/main/res/layout/activity_product_details.xml
  app/src/main/res/layout/custom_product_list_layout.xml
Labels: short

#26 Raman branch
  .gitignore
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/pizza_singh_capstone_project/activities/MainActivity.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/activities/ProductDetailsActivity.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/database/AppDatabase.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/fragments/AccountFragment.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/interfaces/CartDAO.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/models/CartModel.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/repositories/CartRepository.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/utils/SharedPref.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/viewmodels/CartViewModel.kt
  app/src/main/res/layout/activity_product_details.xml
  app/src/main/res/layout/fragment_account.xml
Labels: medium

#28 [#8] Add to cart functionality done with room database and closes #8
  .idea/deploymentTargetDropDown.xml
Labels: long

#29 Sohail branch
  .DS_Store
  app/.DS_Store
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/pizza_singh_capstone_project/adapters/CartsListAdapter.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/fragments/AccountFragment.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/fragments/CartFragment.kt
  app/src/main/res/drawable/baseline_shopping_cart_24.xml
  app/src/main/res/layout/activity_product_details.xml
  app/src/main/res/layout/custom_cart_list.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: medium

#30 [#6] subcategory screen done with search functionality and closes #6
  app/src/main/java/com/example/pizza_singh_capstone_project/activities/ProductListActivity.kt
  app/src/main/java/com/example/pizza_singh_capstone_project/adapters/ProductListAdapter.kt
  app/src/main/res/menu/search_menu.xml
Labels: medium
